### ISSUE TITLE
Requires unknown system CONTAINER-DYNAMIC-CLASSES

### ISSUE THREAD

**Issue by quicklisp** [gwkkwg/cl-markdown#1]
I'm trying to build this library on SBCL, and I get this error:

    :CONTAINER-DYNAMIC-CLASSES not found, required by #<SYSTEM "cl-markdown">

What should I do?

**Comment by fewdea** [comment]
Any updates on this?

**Comment by hraban** [comment]
If you have `asdf-system-connections` available on your ASDF path you won't need the mysterious `container-dynamic-classes` package anymore. It seems the latter is obsolete, so I probably should just make asdf-system-connections a hard requirement, tbh.
